name: Dash Component

on:
  push:
    branches:
      - main
      - staging
      - develop
      - EDE-673

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: checking repository
        uses: actions/checkout@v2
      - name: Load AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy
        uses: docker://public.ecr.aws/o2j0s4o1/github_action_base:latest
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          entrypoint: devops/deployment.sh